### ISSUE TITLE
如何提取图片原图？

### ISSUE THREAD

**Issue by Kiana1314** [jcjrobert/nonebot-plugin-bilibili-image#2]

**Comment by Kiana1314** [comment]
![MZH0D768`6DHB00G@@12%9U](https://user-images.githubusercontent.com/107671434/208818296-f451a2b6-3ea2-421a-976e-a2b1094b100f.png)

**Comment by jcjrobert** [comment]
上传文件的压缩包里是原图，
转发消息里的图片不是原图，因为会被tx压缩，
如果要提取，就是下载群文件的图片，
或者你等一段时间我单独做一个Windows端的提取器好了（x）
