### ISSUE TITLE
专栏下载失败

### ISSUE THREAD

**Issue by Kiana1314** [jcjrobert/nonebot-plugin-bilibili-image#3]
![~JI63X%Y}95M) XT55RL3R5](https://user-images.githubusercontent.com/107671434/208818836-956f6d4e-4adf-48e4-bfca-6832451bf22f.png)
![PG31XW4Z5C(JQO78_@J@{9A](https://user-images.githubusercontent.com/107671434/208818900-8e297ef7-e37d-4844-91c7-9e1e73bb156a.png)

**Comment by jcjrobert** [comment]
可以看看是哪个专栏么（x）

一般来说，要提取图片很多的专栏的图片，最后的压缩包文件会很大，很大的文件就意味着很容易上传失败，这没办法（x）
你给的日志只有网络超时的报错，暂时没有办法，或者我想想做个切割什么的

**Comment by Kiana1314** [comment]
随便找的一个专栏  也没多少图片
https://www.bilibili.com/read/cv4219968?spm_id_from=333.999.0.0
有时可以抓取到图片
![2O5ABJ7%NJ_BP8SO D2FSOI](https://user-images.githubusercontent.com/107671434/209077552-2255d87b-280d-4f03-ada4-4a31e7f21c59.png)
但是上传文件总是失败，群上转权限是打开的

**Comment by jcjrobert** [comment]
> 随便找的一个专栏 也没多少图片 https://www.bilibili.com/read/cv4219968?spm_id_from=333.999.0.0 有时可以抓取到图片 ![2O5ABJ7%NJ_BP8SO D2FSOI](https://user-images.githubusercontent.com/107671434/209077552-2255d87b-280d-4f03-ada4-4a31e7f21c59.png) 但是上传文件总是失败，群上转权限是打开的

我试了一下，运行正常，图片13M
看起来是windows的网络问题？
目前来看是没什么办法，图片也不大，我这里100M的图片都能上传
是gocq版本问题么，是最新版么

**Comment by Kiana1314** [comment]
v1.0.0-rc3
![30IN`V`T(T$I(RENJGKALQS](https://user-images.githubusercontent.com/107671434/209352963-00b4b9ff-b78b-4ff7-9d3d-cb1a090b6e3b.png)

服务器重启了下 还是上传失败
![BTO6A$OU8U9EOO@VO ~HTV](https://user-images.githubusercontent.com/107671434/209353182-8fd8eee7-0b94-4b9a-a259-83bda5493a2b.png)

**Comment by jcjrobert** [comment]
了解了，下个版本加个下到本地的设置这样应该能解决问题吧（x

**Comment by jcjrobert** [comment]
已更新，请更新至最新版本，保存在本地需要设置
